### ISSUE TITLE
No support for other architectures

### ISSUE THREAD

**Issue by Andy3153** [viperML/in-nix#2]
Is there any reason in particular that the flake has an output for packages only for `x86_64-linux`? I saw it would fail to rebuild on my RPi 4, and this seems to be only a limitation of the flake. The code seems simple enough and not at all architecture-specific.

I could make a pull request to add a helper function that automatically adds every package this flake outputs to every arch NixOS supports.

**Comment by viperML** [comment]
The reason is that I only use this on `x86_64-linux` machines. It probably works the same in ARM, and I have no idea about macOS.

**Comment by Andy3153** [comment]
And, do you want me to do something about the issue, or you don't want to implement a fix?
